// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0LppH-2ij3VwCCMLA9tGHKrnKCft-IfI',
    appId: '1:995411517879:web:c30f00a0b58b9f18320832',
    messagingSenderId: '995411517879',
    projectId: 'kpa-erp-ridhi-20-19d52',
    authDomain: 'kpa-erp-ridhi-20-19d52.firebaseapp.com',
    storageBucket: 'kpa-erp-ridhi-20-19d52.firebasestorage.app',
    measurementId: 'G-VNP64PGLSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGoVSeh-aDyJkwxmmdZq7AeD-6AR8Dd08',
    appId: '1:995411517879:android:a5c441d99d478105320832',
    messagingSenderId: '995411517879',
    projectId: 'kpa-erp-ridhi-20-19d52',
    storageBucket: 'kpa-erp-ridhi-20-19d52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnicRBnSE9_0I_IsPDfrCqkZEI7Vi-HwQ',
    appId: '1:995411517879:ios:5760e4341dba4bc0320832',
    messagingSenderId: '995411517879',
    projectId: 'kpa-erp-ridhi-20-19d52',
    storageBucket: 'kpa-erp-ridhi-20-19d52.firebasestorage.app',
    iosBundleId: 'com.example.kpaErp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0LppH-2ij3VwCCMLA9tGHKrnKCft-IfI',
    appId: '1:995411517879:web:5891680e901d66b6320832',
    messagingSenderId: '995411517879',
    projectId: 'kpa-erp-ridhi-20-19d52',
    authDomain: 'kpa-erp-ridhi-20-19d52.firebaseapp.com',
    storageBucket: 'kpa-erp-ridhi-20-19d52.firebasestorage.app',
    measurementId: 'G-FJCHYZFYKY',
  );
}
